name: NPM Project CI/CD with Unit Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # or 'npx yarn' if you're using Yarn

      - name: Run Jest tests
        run: npx jest

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: dist

  unit-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # or 'npx yarn' if you're using Yarn

      - uses: actions/download-artifact@v3
        with:
          name: assets
          path: dist

      - name: Run Unit Tests
        run: npx jest # Assuming 'jest' is defined under the 'test' script in package.json

