name: Secrets Management
on: [push, pull_request]

jobs:
  build:
    steps:
      - name: build
        run: ./build.sh "${{ secrets.ASSETS_UPLOADER_KEY }}" "${{ secrets.ASSETS_UPLOADER_SECRET }}"
        timeout-minutes: 15
